name: Deploy Theme to Branch

# Хэзээ ажиллах вэ? 
# Master бранч руу push хийгдэх үед (Gitflow release дуусах үед)
on:
  push:
    branches:
      - master # Хэрэв таны main бранч нь 'main' гэж нэрлэгддэг бол энд 'main' гэж солиорой.

permissions:
  contents: write # Бранч руу бичих эрх олгох

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Кодыг бүгдийг нь татаж авах
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Theme фолдерыг theme бранч руу хуулах
      - name: Push directory to theme branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: theme # Файлуудыг оруулах бранчийн нэр
          FOLDER: theme # Хуулах гэж буй фолдерын нэр
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub-аас өгдөг автомат token
          MESSAGE: "Release: Sync theme folder from master ({sha})" # Commit message